Adding 'Upload' Function and sample test json
CatalystCode/active-learning-detect pull request #11
Opened 2018-10-26 23:07 UTC by mtarng

Unsure if we want to merge this as-is. This is the function code that's running on Azure Function currently. It still needs to be modified to call the integrating functions to the database. Do we also need to include template/deploy scripts on this?

2018-10-26 23:18 UTC, bnookala commented
Check out the style and formatting samples for stuff here https://github.com/yokawasa/azure-functions-python-samples/tree/master/http-trigger-dump-request/function

autopep8 also

2018-10-26 23:18 UTC, bnookala requested changes
style and azure function definition json

2018-10-29 22:20 UTC, andrebriggs commented
@mtarng any reason not to use the default __init__.py file name for the functions entry point?

2018-10-29 22:22 UTC, andrebriggs commented on functions/upload/run.py
> +def process_vott_json(json):
@mtarng eventually process_vott_json and get_id_from_filename() should be in a separate file. This way we aren't coupled to the the implementation of Azure Functions

2018-10-29 22:25 UTC, mtarng commented
> @mtarng any reason not to use the default **init**.py file name for the functions entry point?

Just mimic'ing the default names generated by Azure. I'll change it up; learning Python as we go, please let me know standards/best practices as you see them 😄

2018-10-29 22:30 UTC, andrebriggs reviewed
> > @mtarng any reason not to use the default **init**.py file name for the functions entry point?
> 
> Just mimic'ing the default names generated by Azure. I'll change it up; learning Python as we go, please let me know standards/best practices as you see them 😄

See https://github.com/CatalystCode/active-learning-detect/blob/master/functions/pipeline/download/

2018-10-29 22:30 UTC, andrebriggs commented on functions/upload/run.py
> +def process_vott_json(json):
@mtarng eventually process_vott_json and get_id_from_filename() should be in a separate file. This way we aren't coupled to the the implementation of Azure Functions

2018-10-30 02:02 UTC, andrebriggs approved these changes

2018-10-30 21:19 UTC, bnookala approved these changes

2018-10-30 21:19 UTC, merged